version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/requirements" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys-sphinx-theme"
    assignees:
      - "Samuelopez-ansys"
      - "SMoraisAnsys"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "BUILD(pip)"
    groups:
      # Actions related to this repo's CI/CD
      documentation:
        patterns:
          - "ansys-sphinx-theme"
          - "ipython"
          - "jupyterlab"
          - "nbsphinx"
          - "numpydoc"
          - "pypandoc"
          - "recommonmark"
          - "Sphinx"
          - "sphinx*"
          - "jupytext"
          - "nbconvert"
      examples:
        patterns:
          - "imageio"
          - "matplotlib"
          - "numpy"
          - "openpyxl"
          - "osmnx"
          - "pandas"
          - "pyvista"
          - "fast-simplification"
          - "joblib"
          - "plotly"
          - "scikit-rf"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/actions"
    assignees:
      - "Samuelopez-ansys"
      - "SMoraisAnsys"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "BUILD(actions)"

  - package-ecosystem: "pre-commit"
    cooldown:
      default-days: 7 # Fallback cooldown if no specific rule applies
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/pre-commit-hooks"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Paris"
    assignees:
      - "Samuelopez-ansys"
      - "SMoraisAnsys"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "BUILD(pre-commit)"