documentation:
- changed-files:
  - any-glob-to-any-file: doc/source/**/*
maintenance:
- changed-files:
  - any-glob-to-any-file: .github/**/*
  - any-glob-to-any-file: .flake8
dependencies:
- changed-files:
  - any-glob-to-any-file: requirements/*