repos:

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    # exclude: ^(ansys/rep/common/jms/resource/|ansys/rep/common/auth/resource/)

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    # exclude: ^(ansys/rep/common/jms/resource/|ansys/rep/common/auth/resource/)
    additional_dependencies: [pep8-naming]
    # additional_dependencies: [
    #     flake8-alfred, flake8-bugbear, flake8-builtins, flake8-comprehensions,
    #     flake8-docstrings, flake8-eradicate, flake8-print, flake8-pytest-style,
    #     flake8-todo, flake8-unused-arguments, pep8-naming, pydocstyle, Pygments,
    # ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    # exclude: >
    #   (?x)^(
    #       .*\.dat|
    #       .*\.mac|
    #       .*\.k
    #   )$
    # args: [-I, .codespellignore, --ignore-long-lines]

# For now we disable some of these checks, can be reenabled later
# - repo: https://github.com/pycqa/pydocstyle
#   rev: 6.1.1
#   hooks:
#   - id: pydocstyle
#     additional_dependencies: [toml]
#     exclude: "tests/"
