version: "3.9"

secrets:
  netrc:
    file: ${NETRC_PATH}

services:
  repo-template:
    build:
      context: .
      dockerfile: docker/Dockerfile.${TARGET_IMAGE}
      secrets:
        - netrc
    image: ansys.rep.repo-template-${TARGET_IMAGE}:1.0.0
    container_name: rep-repo-template-${TARGET_IMAGE}
    restart: unless-stopped
    command: sleep infinity
    volumes:
      - ./tests:/app/tests
